# Generated by Django 5.0.3 on 2024-03-31 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
