# Generated by Django 5.0.3 on 2024-03-31 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz2app', '0005_remove_customer_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
