# Generated by Django 5.0.3 on 2024-04-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz2app', '0021_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='view_products',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(),
        ),
    ]
