# Generated by Django 4.2.11 on 2024-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Throws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res_throws", models.CharField(max_length=5)),
                ("time_throws", models.TimeField()),
            ],
        ),
    ]
