# Generated by Django 5.0.3 on 2024-03-29 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0002_alter_throws_time_throws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throws',
            name='time_throws',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 19, 4, 25, 954279, tzinfo=datetime.timezone.utc)),
        ),
    ]
