# Generated by Django 5.0.3 on 2024-04-04 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0005_author_alter_throws_time_throws'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_bones', models.IntegerField()),
                ('time_bones', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_random', models.IntegerField()),
                ('time_random', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
